# Generated by Django 5.1.7 on 2025-03-21 21:33

import konveyor.apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/', validators=[konveyor.apps.documents.models.validate_file_extension]),
        ),
    ]
