name: "App CI/CD (Test Environment)"

permissions:
  contents: read # Default required for checkout

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.0, v1.2.3
  workflow_dispatch:
    inputs:
      ref:
        description: 'The branch, tag or SHA to deploy (e.g., main, v1.0.0)'
        required: true
        type: string

env:
  AZURE_WEBAPP_NAME: konveyor-test-app
  AZURE_RESOURCE_GROUP: konveyor-test-rg
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  build-and-deploy:
    name: Build and Deploy to Azure App Service (Test)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (push/tag)
        if: github.event_name == 'push' && github.ref_type == 'tag'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Checkout repository (workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ github.ref_name }}
          docker build -t ghcr.io/${{ github.repository }}/konveyor:$IMAGE_TAG .

      - name: Push Docker image to GHCR
        run: |
          IMAGE_TAG=${{ github.ref_name }}
          docker push ghcr.io/${{ github.repository }}/konveyor:$IMAGE_TAG

      - name: Azure Login
        uses: azure/login@v2.1.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App (using GHCR image)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          resource-group-name: ${{ env.AZURE_RESOURCE_GROUP }}
          images: ghcr.io/${{ github.repository }}/konveyor:$IMAGE_TAG
