name: "App CI/CD (Test Environment)"

on:
  push:
    branches:
      - main
      - feature/task-1-infra-cicd
    paths:
      - 'konveyor/**'
      - 'requirements/**'
      - 'manage.py'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    paths:
      - 'konveyor/**'
      - 'requirements/**'
      - 'manage.py'
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: konveyor-test-app
  AZURE_RESOURCE_GROUP: konveyor-test-rg
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  build-and-deploy:
    name: Build and Deploy to Azure App Service (Test)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/production.txt

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          resource-group-name: ${{ env.AZURE_RESOURCE_GROUP }}
          package: .
