name: "Build and Push Docker Image"

permissions:
  contents: read   # Required for checkout
  id-token: write  # Required for Azure login
  packages: write  # Required for pushing to GHCR

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'The branch, tag or SHA to deploy (e.g., main, v1.0.0)'
        required: true
        type: string
      environment:
        description: 'Environment to deploy to (dev, test, prod)'
        required: false
        default: 'test'
        type: choice
        options:
          - dev
          - test
          - prod
  workflow_call:
    inputs:
      ref:
        description: 'The branch, tag or SHA to deploy (e.g., main, v1.0.0)'
        required: false
        type: string
      environment:
        description: 'Environment to deploy to (dev, test, prod)'
        required: false
        default: 'test'
        type: string
    secrets:
      GHCR_PAT:
        description: 'GitHub Container Registry Personal Access Token'
        required: true
    outputs:
      image_tag:
        description: "The Docker image tag that was built"
        value: ${{ jobs.build.outputs.image_tag }}

env:
  # Default image tag if not set elsewhere
  IMAGE_TAG: latest

jobs:
  build:
    name: "Build and Push Docker Image"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      image_tag: ${{ steps.set_tag.outputs.image_tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.event.inputs.ref || github.ref }}

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set Image Tag
        id: set_tag
        run: |
          if [ "${{ github.ref_type }}" == "tag" ]; then
            echo "image_tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "image_tag=${{ github.event.inputs.ref }}" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" == "workflow_call" ]; then
            echo "image_tag=${{ inputs.ref || 'latest' }}" >> $GITHUB_OUTPUT
          else
            echo "image_tag=latest" >> $GITHUB_OUTPUT
          fi
          echo "Using image_tag: ${{ steps.set_tag.outputs.image_tag }}"
          echo "IMAGE_TAG=${{ steps.set_tag.outputs.image_tag }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }} .

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }}
