name: "Code Quality Checks"

on:
  pull_request:
    branches: [ main, dev ]
  push:
    branches: [ main, dev ]
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    name: Lint Python Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort

      - name: Check code formatting with Black
        run: |
          black --check --diff konveyor tests

      - name: Check import sorting with isort
        run: |
          isort --check --diff konveyor tests

      - name: Lint with flake8
        run: |
          flake8 konveyor tests --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 konveyor tests --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  test-coverage:
    name: Test Coverage
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: konveyor.settings.testing
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/testing.txt
          pip install coverage

      - name: Run tests with coverage
        run: |
          coverage run --source=konveyor manage.py test

      - name: Generate coverage report
        run: |
          coverage report
          coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
