name: "Complete CI/CD Pipeline"

on:
  pull_request:
    branches: [ main, dev ]
  push:
    branches: [ main, dev ]
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy to Azure after tests'
        required: false
        default: false
        type: boolean
      test_type:
        description: 'Type of tests to run'
        required: true
        default: 'mock'
        type: choice
        options:
          - mock
          - real
          - both
      environment:
        description: 'Environment to run tests in'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test
          - prod
      test_category:
        description: 'Category of tests to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - unit
          - integration
          - real
          - search
          - document
          - slack
      fast_track:
        description: 'Run only critical tests for quick deployment'
        required: false
        default: false
        type: boolean
      ref:
        description: 'The branch, tag or SHA to deploy (e.g., main, v1.0.0)'
        required: false
        type: string

jobs:
  # Step 1: Check branch naming conventions
  branch-naming:
    name: "Validate Branch Naming"
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/commit-conventions.yml

  # Step 2: Run code quality checks
  code-quality:
    name: "Code Quality Checks"
    needs: [branch-naming]
    if: always() && (needs.branch-naming.result == 'success' || needs.branch-naming.result == 'skipped')
    uses: ./.github/workflows/code-quality.yml

  # Step 3: Run integration tests
  integration-tests:
    name: "Integration Tests"
    needs: [code-quality]
    if: always() && (needs.code-quality.result == 'success' || needs.code-quality.result == 'skipped')
    uses: ./.github/workflows/integration-tests.yml
    with:
      test_type: ${{ github.event.inputs.test_type || 'mock' }}
      environment: ${{ github.event.inputs.environment || 'dev' }}
      test_category: ${{ github.event.inputs.test_category || 'all' }}
      fast_track: ${{ github.event.inputs.fast_track || false }}

  # Step 4: Deploy to Azure App Service (if requested or on tag)
  deploy:
    name: "Deploy Application to Azure"
    needs: [integration-tests]
    if: |
      always() &&
      needs.integration-tests.outputs.success == 'true' &&
      (github.event.inputs.deploy == 'true' || github.ref_type == 'tag' || startsWith(github.ref, 'refs/tags/v'))
    uses: ./.github/workflows/deploy-app.yml
    with:
      ref: ${{ github.event.inputs.ref || github.ref }}
      environment: ${{ github.event.inputs.environment || 'test' }}

  # Step 5: Deploy infrastructure (if needed)
  deploy-infra:
    name: "Deploy Infrastructure"
    needs: [integration-tests]
    if: |
      always() &&
      needs.integration-tests.outputs.success == 'true' &&
      (github.event.inputs.deploy == 'true' || github.ref_type == 'tag' || contains(github.ref, 'infra'))
    uses: ./.github/workflows/infra-test.yml
    with:
      ref: ${{ github.event.inputs.ref || github.ref }}
      environment: ${{ github.event.inputs.environment || 'test' }}
